apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend
data:
  AUTH_PORT: "5005"
  PRODUCT_PORT: "5001"
  CART_PORT: "5002"
  ORDER_PORT: "5003"
  PAYMENT_PORT: "5004"
  EMAIL_PORT: "5006"

  NODE_ENV: "production"
  SEED_SAMPLE_DATA: "true"

  AWS_REGION: "ap-south-1"
  S3_BUCKET_NAME: "devops-project-frontend-rajesh"

  DB_HOST: "REPLACE_DB_ENDPOINT"

  TEST_EMAIL: "rark21ec@cmrit.ac.in"
  EMAIL_USER: "rajesha100920@gmail.com"

  ORDERS_SERVICE_URL: "REPLACE_ORDERS_ALB_DNS"

  STRIPE_PUBLISHABLE_KEY: ""